# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Quoc Duong Nguyen
title: Audio Software Engineer @ Télécom Paris
email: quoc-duong.nguyen@outlook.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: quocduongn
github_username:  quoc-duong
instagram_username: quocduong_n
# orcid_username: 0000-0002-0101-1604

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hello there, my name's Quoc Duong and I'm a master's student in computer science student at EPITA, specialized in AI and health.

  I am most skilled in: <mark>Machine learning</mark> and <mark>Drinking bubble tea</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Demixr
        link: github.com/demixr/demixr-app
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/demixr
        description: | # this will include new lines to allow paragraphs
            Open source music demixing application on mobile using PyTorch Mobile.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Télécom Paris
        link: https://adasp.telecom-paris.fr/
        link_text: adasp.telecom-paris.fr
        sub_title: Audio Software Engineer
        caption: November 2023 - Now
        description: | # this will include new lines to allow paragraphs
            Real-time audio processing on <mark>Android</mark> and <mark>iOS</mark> in the ADASP group of the LTCI laboratory.
      - layout: left
        title: BOpA/Inria - Bernoulli Lab
        link: https://www.bernoulli-lab.fr/project/chaire-bopa/
        link_text: bernoulli-lab.fr
        sub_title: Machine Learning Intern
        caption: Mars 2022 - Août 2022
        description: | # this will include new lines to allow paragraphs
            Deep learning and augmented reality to assist with liver resection.
      - layout: left
        title: EPITA
        link: epita.fr
        link_text: epita.fr
        sub_title: Teaching Assistant
        caption: August 2021 - January 2022
        description: | # this will include new lines to allow paragraphs
            Teaching <mark>C</mark>, <mark>Unix</mark>, <mark>Python</mark>, <mark>SQL</mark> and the fundamentals of programming to third year students. Manager of the malloc project.
      - layout: left
        title: SAP
        link: sap.com
        link_text: sap.com
        sub_title: Fullstack Developer Intern
        caption: September 2020 - January 2021
        description: | # this will include new lines to allow paragraphs
            Development of a web application which aims to group and search specific resources using <mark>React.js</mark>, <mark>Java</mark>, <mark>MongoDB</mark>, <mark>Jira</mark>.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: "Universitat Pompeu Fabra"
        caption: 2022 - 2023
        link: https://www.upf.edu/web/smc
        link_text: upf.edu
        sub_title: Master in Sound and Music Computing
        description: | # this will include new lines to allow paragraphs
            - Master thesis on automatic score-to-score music generation.
            - Courses: Audio Signal Processing, Music Perception and Cognition, Music Information Retrieval, Audio and Music Processing, Research Methods, Natural Language Interaction
      - layout: left
        title: "EPITA: School of Engineering and Computer Science"
        caption: 2017 - 2022
        link: epita.fr
        link_text: epita.fr
        sub_title: MSc in Computer Science
        description: | # this will include new lines to allow paragraphs
            - Majoring in AI/Healthcare: Deep learning, Medical imaging, bioinformatics, High Performance Computing, Standards and interoperability. AP-HP, Doctolib.
            - International Section: Courses are taken in English during the first three years.
      - layout: left
        title: "University of Seoul - 서울시립대학교"
        caption: February 2019 - June 2019
        link: uos.ac.kr
        link_text: uos.ac.kr
        sub_title: Academic Exchange Semester
        description: | # this will include new lines to allow paragraphs
            Courses: Computer Architecture, Formal Languages and Compilers, Introduction to Operating Systems, Discrete Mathematics, Beginning Korean, Pronunciation of Korean.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computer science, some of my other interests and hobbies are:
      - Music: Singing, classical guitar
      - Gaming
      - Climbing

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
